<?php
    //se o usuario tiver preenchido e enviado o form, vai entrar nesse if
    if (false === empty($_POST)) {
        $nome = $_POST['nome'];
        $email = $_POST['email'];
        $senha = $_POST['senha'];

        $now = date('Y-m-d H:i:s');
        $sql = "
            INSERT INTO tb_usuarios 
                (nome, email, senha, criado_em, atualizado_em, ultimo_login)
            VALUES
                ('{$nome}', '{$email}', '{$senha}', '{$now}', '{$now}', '{$now}')
            ";

        include '../src/conexao.php';
        

        // statement é o preparo da query, antes de ser executada
        try{

            $statement = $pdo->query($sql);
        echo "<div class='alert alert-success mt-4'>
            <strong>Pronto!</strong>
            Novo Usuário criado!<br>

            <a href='/'>Entrar</a>
        </div>";
        }catch(PDOException $e){
            if($e->errorInfo[1] == 1062){
                echo "<div class='alert alert-danger'>
            <strong>Erro:</strong>
            Usuário já cadastrado como e-mail: {$email}!</div>";
//
            }else{
                echo "Erro:". $e-> getMessage();
            }
        }
        
        
        
    }
?>



<section class="row mt-5">
    <div class="col-4 offset-4 mt-5">
        <div class="card card-body">
            <h1>Cadastro de Usuário</h1>
            <hr>

            <form action="" method="post">
                <input name="nome" type="text" class="form-control form-control-lg mb-3" placeholder="Nome">

                <input name="email" type="email" class="form-control form-control-lg mb-3" placeholder="Email">
    
                <input name="senha" type="password" class="form-control form-control-lg mb-3" placeholder="Senha">
    
                <button class="btn btn-primary btn-lg w-100">ENTRAR</button>

                <p class="mt-3 text-end">
                    Já tem conta? <br>
                    <a href="/login">Login</a>
                </p>
            </form>
        </div>
    </div>
</section>