<?php
include '../src/conexao.php';

$id = $_SESSION['user']['id'];

$sql = "SELECT * FROM tb_usuarios WHERE id=:id";

$statement = $pdo->prepare($sql);
$statement->execute([
    ':id' => $id,
]);

$user = $statement->fetch(PDO::FETCH_ASSOC);

//se o usuario tiver enviado o form
if (false === empty($_POST)) {
    $nome = $_POST['nome'];
    $email = $_POST['email'];

    // TODO: editar a senha
    $senha = $_POST['senha'];

    $now = new DateTime();

    $atualizarSenha = "";

    if ($senha !== '') {
        $atualizarSenha = 'senha=:senha,';
    }

    $sql = "UPDATE tb_usuarios 
            SET 
                nome=:nome, 
                email=:email, 
                {$atualizarSenha}
                atualizado_em=:atualizado_em 
            WHERE id=:id";

    $statement = $pdo->prepare($sql);
    
    $params = [
        ':nome' => $nome,
        ':email' => $email,
        ':atualizado_em' => $now->format('Y-m-d H:i:s'),
        ':id' => $id,
    ];

    if ($senha !== '') {
        $params[':senha'] = password_hash($senha, PASSWORD_BCRYPT);
    }

    $statement->execute($params);

    echo '<script> location.href = ""; </script>';
}
?>

<section class="card card-body">
    <h3>
        <i class="material-icons fs-1">person</i>
        <?php echo $_SESSION['user']['nome']; ?>
    </h3>

    <hr>

    <div class="alert alert-info">
        <strong>Criado em: </strong> <?php echo $user['criado_em']; ?> 
        <br>
        <strong>Atualizado em: </strong> <?= $user['atualizado_em'] ?>
        <br>
        <strong>Último Login: </strong> <?= $user['ultimo_login'] ?> 
    </div>

    <form action="" method="post">
        <input name="nome" value="<?= $user['nome'] ?>" type="text" class="form-control form-control-lg mb-3" placeholder="Nome">

        <input name="email" value="<?= $user['email'] ?>" type="email" class="form-control form-control-lg mb-3" placeholder="Email">

        <input name="senha" type="password" class="form-control form-control-lg mb-3" placeholder="Senha (Preencha apenas se quiser mudar)">

        <button class="btn btn-primary btn-lg w-100">ATUALIZAR</button>
    </form>
</section>
