<hr>

<div class="row align-items-center">
    <div class="col">
        <h1> 
            <i class="material-icons fs-1">groups</i>
            CONTATINHOS
        </h1>
    </div>
    <div class="col text-end">
        <a class="btn btn-outline-dark" href="/">
            <i class="material-icons">home</i>
            Inicio
        </a>
        <a class="btn btn-outline-dark" href="/contatos/cadastro">
            <i class="material-icons">person_add</i>
            Cadastrar
        </a>
        <a class="btn btn-outline-dark" href="/contatos/listar">
            <i class="material-icons">person_search</i>
            Listar
        </a>
        
        <div class="dropdown d-inline">
            <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="material-icons">person</i>
                <?php echo $_SESSION['user']['nome']; ?>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/usuario/perfil">Perfil</a></li>
                <li><a class="dropdown-item" href="/sair">Sair</a></li>
            </ul>
        </div>
    </div>
</div>
<hr>